-- 문제 1.
SELECT DEPT_CODE, SUM(SALARY) 합계, FLOOR(AVG(SALARY)) 평균, COUNT(*) 인원수
FROM EMPLOYEE
GROUP BY DEPT_CODE
HAVING AVG(SALARY) > 2800000
ORDER BY 1 ASC;

---------------------------------------------------------------------
-- 문제 2.
SELECT EMP_NAME, SALARY

FROM EMPLOYEE

ORDER BY SALARY DESC NULLS LAST;

SELECT *
FROM (SELECT EMP_NAME, SALARY

        FROM EMPLOYEE

        ORDER BY SALARY DESC NULLS LAST)
WHERE ROWNUM <= 3;

