CREATE TABLE TB_PHONEBOOK(
    USERNO NUMBER PRIMARY KEY,          -- 회원번호
    USERNAME VARCHAR2(20) NOT NULL,     -- 회원명
    AGE NUMBER NOT NULL,                -- 나이
    ADDRESS VARCHAR2(100) NOT NULL,     -- 주소
    PHONE VARCHAR2(13) NOT NULL         -- 전화번호
);

ALTER TABLE TB_PHONEBOOK ADD UNIQUE(PHONE);

SELECT * FROM TB_PHONEBOOK;

CREATE SEQUENCE SEQ_PHONEBOOK
NOCACHE
;

COMMENT ON COLUMN TB_PHONEBOOK.USERNO IS '회원번호';
COMMENT ON COLUMN TB_PHONEBOOK.USERNAME IS '회원명';
COMMENT ON COLUMN TB_PHONEBOOK.AGE IS '나이';
COMMENT ON COLUMN TB_PHONEBOOK.ADDRESS IS '주소';
COMMENT ON COLUMN TB_PHONEBOOK.PHONE IS '전화번호';

ALTER TABLE TB_PHONEBOOK RENAME CONSTRAINT SYS_C007334 TO PK_USERNO;
ALTER TABLE TB_PHONEBOOK RENAME CONSTRAINT SYS_C007335 TO UQ_PHONE;

INSERT INTO TB_PHONEBOOK VALUES (SEQ_PHONEBOOK.NEXTVAL, ?, ?, ?, ?);