CREATE TABLE TEST(
    TEST_NO NUMBER
);

SELECT * FROM KH.EMPLOYEE;

INSERT INTO TEST (SELECT EMP_ID FROM KH.EMPLOYEE);

SELECT * FROM TEST;

DELETE FROM TEST
WHERE TEST_NO = 203;

SAVEPOINT SP;

UPDATE TEST
SET TEST_NO = 100
WHERE TEST_NO = 200;

CREATE TABLE TEST2(
    TEST_ID VARCHAR2(10)
);

ROLLBACK;

INSERT INTO TEST VALUES(203);
INSERT INTO TEST(TEST_NO) VALUES (303);

ALTER TABLE TEST ADD TEST_ID VARCHAR2(10);

ALTER TABLE TEST ADD PRIMARY KEY(TEST_NO);

ALTER TABLE TEST RENAME CONSTRAINT SYS_C007260 TO TEST_NO_PK;

ALTER TABLE TEST DROP COLUMN TEST_ID;