CREATE TABLE TB_TEST3(
    TEST_NO NUMBER PRIMARY KEY
);

SELECT * FROM TB_TEST3;

CREATE SEQUENCE SEQ_TEST
NOCACHE;

INSERT INTO TB_TEST3 VALUES(SEQ_TEST.NEXTVAL);

DELETE FROM TB_TEST3;

ALTER TABLE TB_TEST3 ADD TEST_NAME VARCHAR2(20) UNIQUE NOT NULL;

ALTER TABLE TB_TEST3 ADD TEST_DATE DATE DEFAULT SYSDATE;

ALTER TABLE TB_TEST3 MODIFY TEST_DATE DEFAULT '01/01/01';

INSERT INTO TB_TEST3 VALUES (SEQ_TEST.NEXTVAL, 'YOON', DEFAULT);

ALTER TABLE TB_TEST3 ADD TSET_ID VARCHAR2(20) UNIQUE;

ALTER TABLE TB_TEST3 DROP COLUMN TSET_ID;

ROLLBACK;

COMMIT;

/*
CREATE VIEW VW_TEST
AS SELECT * FROM TB_TEST3;
*/